name: theo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
dependencies:
  cron: ^0.6.0
  dotenv: ^4.2.0
  http: ^1.2.1
